name: Split subpackages to their own repos

on:
  push:
    branches: [ main ]   # keep split repos' default branches current
    tags: [ "v*" ]       # push the same tag to each split repo

permissions:
  contents: read

concurrency:
  group: "split-${{ github.ref }}"
  cancel-in-progress: false

jobs:
  split:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - { local_path: "laminas-bridge", split_repository: "php-reader-laminas" }
          - { local_path: "symfony-bundle", split_repository: "php-reader-symfony" }
          - { local_path: "laravel-bridge", split_repository: "php-reader-laravel" }

    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Split on branch pushes (no tag)
      - name: Split branch
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: danharrin/monorepo-split-github-action@v2.3.0
        with:
          package_directory: "packages/${{ matrix.package.local_path }}"
          repository_organization: "vollbehr"
          repository_name: "${{ matrix.package.split_repository }}"
          user_name: "github-actions[bot]"
          user_email: "41898282+github-actions[bot]@users.noreply.github.com"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      # Split on tags (propagate the SAME tag name)
      - name: Split tag
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: danharrin/monorepo-split-github-action@v2.3.0
        with:
          tag: "${{ github.ref_name }}"
          package_directory: "packages/${{ matrix.package.local_path }}"
          repository_organization: "vollbehr"
          repository_name: "${{ matrix.package.split_repository }}"
          user_name: "github-actions[bot]"
          user_email: "41898282+github-actions[bot]@users.noreply.github.com"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
